package lockfile

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"bonjoski/argus/internal/model"
)

// NuGetLockParser parses packages.lock.json files generated by NuGet and .NET SDK.
type NuGetLockParser struct{}

type nugetLockFileDoc struct {
	Version      int                                        `json:"version"`
	Dependencies map[string]map[string]nugetLockPackageItem `json:"dependencies"`
}

type nugetLockPackageItem struct {
	Type         string            `json:"type"`
	Requested    string            `json:"requested"`
	Resolved     string            `json:"resolved"`
	ContentHash  string            `json:"contentHash"`
	Dependencies map[string]string `json:"dependencies"`
}

// Parse reads packages.lock.json and extracts all locked .NET dependencies.
func (p *NuGetLockParser) Parse(r io.Reader) ([]LockedDependency, error) {
	body, err := io.ReadAll(io.LimitReader(r, 20*1024*1024))
	if err != nil {
		return nil, fmt.Errorf("failed to read packages.lock.json: %w", err)
	}

	var doc nugetLockFileDoc
	if err := json.Unmarshal(body, &doc); err != nil {
		return nil, fmt.Errorf("failed to parse packages.lock.json: %w", err)
	}

	// Deduplicate by package name + version
	seen := make(map[string]*LockedDependency)
	var orderedKeys []string

	for _, frameworkDeps := range doc.Dependencies {
		for pkgName, entry := range frameworkDeps {
			version := entry.Resolved
			if version == "" {
				version = entry.Requested
			}
			if version == "" {
				continue
			}

			key := fmt.Sprintf("%s@%s", strings.ToLower(pkgName), version)
			isTransitive := strings.EqualFold(entry.Type, "Transitive")

			if existing, exists := seen[key]; exists {
				// If marked direct in any framework, keep it as direct
				if !isTransitive {
					existing.IsTransitive = false
				}
				continue
			}

			hash := ""
			if entry.ContentHash != "" {
				if strings.HasPrefix(entry.ContentHash, "sha512-") || strings.HasPrefix(entry.ContentHash, "sha256-") {
					hash = entry.ContentHash
				} else {
					hash = "sha512-" + entry.ContentHash
				}
			}

			dep := &LockedDependency{
				Name:          pkgName,
				Version:       version,
				Ecosystem:     model.EcosystemNuGet,
				IntegrityHash: hash,
				IsTransitive:  isTransitive,
			}

			seen[key] = dep
			orderedKeys = append(orderedKeys, key)
		}
	}

	result := make([]LockedDependency, 0, len(orderedKeys))
	for _, k := range orderedKeys {
		result = append(result, *seen[k])
	}

	return result, nil
}
