package ast

import (
	"strings"
)

// pythonStdlib contains standard library modules across Python 3.9 through 3.13.
var pythonStdlib = map[string]struct{}{
	"__future__":      {},
	"_thread":         {},
	"abc":             {},
	"aifc":            {},
	"argparse":        {},
	"array":           {},
	"ast":             {},
	"asynchat":        {},
	"asyncio":         {},
	"asyncore":        {},
	"atexit":          {},
	"audioop":         {},
	"base64":          {},
	"bdb":             {},
	"binascii":        {},
	"binhex":          {},
	"bisect":          {},
	"builtins":        {},
	"bz2":             {},
	"cProfile":        {},
	"calendar":        {},
	"cgi":             {},
	"cgitb":           {},
	"chunk":           {},
	"cmath":           {},
	"cmd":             {},
	"code":            {},
	"codecs":          {},
	"codeop":          {},
	"collections":     {},
	"colorsys":        {},
	"compileall":      {},
	"concurrent":      {},
	"configparser":    {},
	"contextlib":      {},
	"contextvars":     {},
	"copy":            {},
	"copyreg":         {},
	"crypt":           {},
	"csv":             {},
	"ctypes":          {},
	"curses":          {},
	"dataclasses":     {},
	"datetime":        {},
	"dbm":             {},
	"decimal":         {},
	"difflib":         {},
	"dis":             {},
	"distutils":       {},
	"doctest":         {},
	"email":           {},
	"encodings":       {},
	"ensurepip":       {},
	"enum":            {},
	"errno":           {},
	"faulthandler":    {},
	"fcntl":           {},
	"filecmp":         {},
	"fileinput":       {},
	"fnmatch":         {},
	"formatter":       {},
	"fpectl":          {},
	"fractions":       {},
	"ftplib":          {},
	"functools":       {},
	"gc":              {},
	"getopt":          {},
	"getpass":         {},
	"gettext":         {},
	"glob":            {},
	"graphlib":        {},
	"grp":             {},
	"gzip":            {},
	"hashlib":         {},
	"heapq":           {},
	"hmac":            {},
	"html":            {},
	"http":            {},
	"idlelib":         {},
	"imaplib":         {},
	"imghdr":          {},
	"imp":             {},
	"importlib":       {},
	"inspect":         {},
	"io":              {},
	"ipaddress":       {},
	"itertools":       {},
	"json":            {},
	"keyword":         {},
	"lib2to3":         {},
	"linecache":       {},
	"locale":          {},
	"logging":         {},
	"lzma":            {},
	"mailbox":         {},
	"mailcap":         {},
	"marshal":         {},
	"math":            {},
	"mimetypes":       {},
	"mmap":            {},
	"modulefinder":    {},
	"msilib":          {},
	"msvcrt":          {},
	"multiprocessing": {},
	"netrc":           {},
	"nis":             {},
	"nntplib":         {},
	"numbers":         {},
	"operator":        {},
	"optparse":        {},
	"os":              {},
	"ossaudiodev":     {},
	"parser":          {},
	"pathlib":         {},
	"pdb":             {},
	"pickle":          {},
	"pickletools":     {},
	"pipes":           {},
	"pkgutil":         {},
	"platform":        {},
	"plistlib":        {},
	"poplib":          {},
	"posix":           {},
	"posixpath":       {},
	"pprint":          {},
	"profile":         {},
	"pstats":          {},
	"pty":             {},
	"pwd":             {},
	"py_compile":      {},
	"pyclbr":          {},
	"pydoc":           {},
	"queue":           {},
	"quopri":          {},
	"random":          {},
	"re":              {},
	"readline":        {},
	"reprlib":         {},
	"resource":        {},
	"rlcompleter":     {},
	"runpy":           {},
	"sched":           {},
	"secrets":         {},
	"select":          {},
	"selectors":       {},
	"shelve":          {},
	"shlex":           {},
	"shutil":          {},
	"signal":          {},
	"site":            {},
	"smtpd":           {},
	"smtplib":         {},
	"sndhdr":          {},
	"socket":          {},
	"socketserver":    {},
	"spwd":            {},
	"sqlite3":         {},
	"ssl":             {},
	"stat":            {},
	"statistics":      {},
	"string":          {},
	"stringprep":      {},
	"struct":          {},
	"subprocess":      {},
	"sunau":           {},
	"symbol":          {},
	"symtable":        {},
	"sys":             {},
	"sysconfig":       {},
	"syslog":          {},
	"tabnanny":        {},
	"tarfile":         {},
	"telnetlib":       {},
	"tempfile":        {},
	"termios":         {},
	"test":            {},
	"textwrap":        {},
	"threading":       {},
	"time":            {},
	"timeit":          {},
	"tkinter":         {},
	"token":           {},
	"tokenize":        {},
	"tomllib":         {},
	"trace":           {},
	"traceback":       {},
	"tracemalloc":     {},
	"tty":             {},
	"turtle":          {},
	"turtledemo":      {},
	"types":           {},
	"typing":          {},
	"unicodedata":     {},
	"unittest":        {},
	"urllib":          {},
	"uu":              {},
	"uuid":            {},
	"venv":            {},
	"warnings":        {},
	"wave":            {},
	"weakref":         {},
	"webbrowser":      {},
	"winreg":          {},
	"winsound":        {},
	"wsgiref":         {},
	"xdrlib":          {},
	"xml":             {},
	"xmlrpc":          {},
	"zipapp":          {},
	"zipfile":         {},
	"zipimport":       {},
	"zlib":            {},
	"zoneinfo":        {},
}

// nodeStdlib contains standard built-in modules for Node.js / ECMAScript.
var nodeStdlib = map[string]struct{}{
	"assert":              {},
	"async_hooks":         {},
	"buffer":              {},
	"child_process":       {},
	"cluster":             {},
	"console":             {},
	"constants":           {},
	"crypto":              {},
	"dgram":               {},
	"diagnostics_channel": {},
	"dns":                 {},
	"domain":              {},
	"events":              {},
	"fs":                  {},
	"http":                {},
	"http2":               {},
	"https":               {},
	"inspector":           {},
	"module":              {},
	"net":                 {},
	"os":                  {},
	"path":                {},
	"perf_hooks":          {},
	"process":             {},
	"punycode":            {},
	"querystring":         {},
	"readline":            {},
	"repl":                {},
	"stream":              {},
	"string_decoder":      {},
	"sys":                 {},
	"timers":              {},
	"tls":                 {},
	"trace_events":        {},
	"tty":                 {},
	"url":                 {},
	"util":                {},
	"v8":                  {},
	"vm":                  {},
	"wasi":                {},
	"worker_threads":      {},
	"zlib":                {},
	"test":                {},
}

// IsPythonStdlib checks if the given top-level module name belongs to the Python standard library.
func IsPythonStdlib(name string) bool {
	clean := strings.TrimSpace(name)
	if idx := strings.Index(clean, "."); idx != -1 {
		clean = clean[:idx]
	}
	_, found := pythonStdlib[clean]
	return found
}

// IsNodeStdlib checks if the given module specifier is a Node.js built-in module.
func IsNodeStdlib(name string) bool {
	clean := strings.TrimSpace(name)
	clean = strings.TrimPrefix(clean, "node:")
	if idx := strings.Index(clean, "/"); idx != -1 {
		clean = clean[:idx]
	}
	_, found := nodeStdlib[clean]
	return found
}

// IsGoStdlib checks if the given import path belongs to Go's standard library.
// Go stdlib packages do not contain a domain name (i.e. dot '.') in their initial path component.
func IsGoStdlib(path string) bool {
	clean := strings.Trim(strings.TrimSpace(path), `"`)
	if clean == "" || clean == "C" {
		return true
	}
	firstSegment := clean
	if idx := strings.Index(clean, "/"); idx != -1 {
		firstSegment = clean[:idx]
	}
	return !strings.Contains(firstSegment, ".")
}

// rustStdlib contains standard crates in the Rust language.
var rustStdlib = map[string]struct{}{
	"std":        {},
	"core":       {},
	"alloc":      {},
	"proc_macro": {},
	"test":       {},
	"crate":      {},
	"super":      {},
	"self":       {},
}

// IsRustStdlib checks if the given crate identifier belongs to Rust std/core or self-referential keywords.
func IsRustStdlib(name string) bool {
	clean := strings.TrimSpace(name)
	_, found := rustStdlib[clean]
	return found
}

// rubyStdlib contains built-in standard gems and libraries in Ruby.
var rubyStdlib = map[string]struct{}{
	"json":         {},
	"yaml":         {},
	"uri":          {},
	"net/http":     {},
	"net/https":    {},
	"fileutils":    {},
	"tempfile":     {},
	"date":         {},
	"time":         {},
	"open-uri":     {},
	"stringio":     {},
	"socket":       {},
	"digest":       {},
	"securerandom": {},
	"base64":       {},
	"csv":          {},
	"benchmark":    {},
	"optparse":     {},
	"logger":       {},
	"set":          {},
	"strscan":      {},
	"zlib":         {},
	"pathname":     {},
	"erb":          {},
	"cgi":          {},
	"openssl":      {},
	"pp":           {},
}

// IsRubyStdlib checks if the required module is part of the Ruby standard library.
func IsRubyStdlib(name string) bool {
	clean := strings.TrimSpace(name)
	_, found := rubyStdlib[clean]
	return found
}
